version: '2'
services:
  unifi:
    image: jacobalberty/unifi:unifi5
    restart: always
    volumes: 
      - /zfs/unifi/data:/var/lib/unifi
      - /zfs/unifi/log:/var/log/unifi
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "3478:3748/udp"
